techpack: Fix -Werror=restrict
 * techpack/audio/asoc/codecs/wcd9xxx-common-v2.c:368:9: error: 'snprintf' argument 4 overlaps destination object 'buf' [-Werror=restrict]
 * Use scnprintf instead of snprintf
https://github.com/PixelExperience-Devices/kernel_realme_sdm710/commit/f5339593c81a4090fcaff74e031d7a419436458b